# Travis CI build file

language: java

cache:
     directories:
        - $HOME/.m2

jdk:
  - oraclejdk11

before_install:
  - wget http://mirrors.london-do.gethosted.online/apache/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.zip 
  - unzip -qq apache-maven-3.6.0-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.6.0
  - export PATH=$M2_HOME/bin:$PATH

before_script:
    - cd build/ant
    - pwd
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

script:
    # This bypasses an issue on the travis CI platform where a connection is made through a proxy and
    # the mirror redirection is not handled correctly by one of the parties.
    - ant

after_success:
    - bash ../build/publish-artifacts.sh
    - bash ../build/publish-website.sh
